spring:
  profiles:
    active:
    - dev
---
server:
  port: 8080 #注册中心占用7001端口,冒号后面必须要有空格

spring:
  profiles: dev
  application:
    name: app-rest

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:8001/eureka/
  instance:
    instance-id: app-rest
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
---
server:
  port: 8080 #注册中心占用7001端口,冒号后面必须要有空格

spring:
  profiles: test
  application:
    name: app-rest

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:8001/eureka/
  instance:
    instance-id: app-rest
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
